---
# ServiceAccount que usan los PipelineRuns para crear pods en el cluster
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline-sa
  namespace: default
  labels:
    app: tekton-demo
---
# ClusterRole con los permisos necesarios para que Tekton gestione recursos
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipeline-role
  labels:
    app: tekton-demo
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "serviceaccounts"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create", "delete", "patch"]
  - apiGroups: ["tekton.dev"]
    resources: ["taskruns", "pipelineruns", "tasks", "pipelines"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
# ClusterRoleBinding: une el SA con el ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipeline-rolebinding
  labels:
    app: tekton-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-pipeline-role
subjects:
  - kind: ServiceAccount
    name: tekton-pipeline-sa
    namespace: default
