apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-demo
  annotations:
    # Inyección automática del sidecar de Linkerd en todos los pods de este namespace
    linkerd.io/inject: enabled
  labels:
    app.kubernetes.io/part-of: linkerd-demo
