# ============================================================
# ETAPA 6 — OPERATE: RBAC mínimo privilegio
# ServiceAccount solo puede leer pods y configmaps del namespace
# ============================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-sa
  # ⚠️  Sin 'namespace:' — usar -n devsecops-demo al aplicar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webapp-role
  # ⚠️  Sin 'namespace:' — usar -n devsecops-demo al aplicar
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list", "watch"]
  # ⚠️  Sin create/delete/patch → mínimo privilegio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapp-rolebinding
  # ⚠️  Sin 'namespace:' — usar -n devsecops-demo al aplicar
subjects:
- kind: ServiceAccount
  name: webapp-sa
  namespace: devsecops-demo   # referencia explícita requerida aquí
roleRef:
  kind: Role
  name: webapp-role
  apiGroup: rbac.authorization.k8s.io
