# ============================================================
# Inventario — Cluster Kubernetes DevOps
# ============================================================

[masters]
k8s-master01  ansible_host=192.168.109.200

[workers]
k8s-worker01  ansible_host=192.168.109.201
k8s-worker02  ansible_host=192.168.109.202

# Grupo k8s = masters + workers
[k8s:children]
masters
workers

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
